server:
  port: 9090

spring:
  application:
    name: API-Gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: AUTHENTICATION-SERVICE
#          uri:  localhost:9091
#          predicates:
#            - Path=/api/v1/authentications/**
#
#        - id: USER-MANAGEMENT-SERVICE
#          uri: localhost:9092
#          predicates:
#            - Path=/api/v1/users/**
#          filters:
#            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true